### ISSUE TITLE
Horizontal Overflow

### ISSUE THREAD

**Issue by geralfonso** [diegoalfonsoc18/Project-portfolio#1]
- There is a horizontal overflow on desktop devices.

![Screen Shot 2022-08-16 at 6 03 58 PM](https://user-images.githubusercontent.com/13323913/185000264-4904926f-fa73-438f-b279-922a00126493.png)

**Comment by diegoalfonsoc18** [comment]
Fix on:
https://github.com/diegoalfonsoc18/Project-portfolio/commit/2fad5c9cc08973b2348906e5390e5d162482d4d7
